// Read-only discovery of the EXISTING BigQuery + Firestore schema.
// Writes a human-readable report to docs/EXISTING_SCHEMA.md (gitignored).
//
// This NEVER writes to BigQuery or Firestore. It only lists/reads metadata
// and a small sample of rows/docs so we can design ingestion + precompute
// against the real schema (per the build plan's "work with existing schema" rule).
//
// Usage (from repo root):  npm run discover
import { BigQuery } from '@google-cloud/bigquery';
import { Firestore } from '@google-cloud/firestore';
import dotenv from 'dotenv';
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, isAbsolute, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SAMPLE_ROWS = 3; // small, just to infer shape — keep low to avoid pulling PII at scale

// ── env ────────────────────────────────────────────────────────────
dotenv.config({ path: resolve(REPO_ROOT, 'credentials/.env') });

// Resolve a possibly-relative GOOGLE_APPLICATION_CREDENTIALS to an absolute path
// so the GCP SDKs can find the key regardless of cwd.
const credRaw = process.env.GOOGLE_APPLICATION_CREDENTIALS;
if (credRaw && !isAbsolute(credRaw)) {
  process.env.GOOGLE_APPLICATION_CREDENTIALS = resolve(REPO_ROOT, credRaw);
}
const projectId = process.env.FIREBASE_PROJECT_ID;
if (!projectId) {
  console.error('FIREBASE_PROJECT_ID missing from credentials/.env');
  process.exit(1);
}

const out = [];
const log = (s = '') => {
  out.push(s);
  console.log(s);
};

const fmt = (v) => {
  if (v === null || v === undefined) return '';
  if (typeof v === 'object') {
    try { return JSON.stringify(v); } catch { return String(v); }
  }
  const s = String(v);
  return s.length > 80 ? s.slice(0, 77) + '…' : s;
};

// ── BigQuery ─────────────────────────────────────────────────────────
async function discoverBigQuery() {
  log('# Existing Schema — BigQuery + Firestore');
  log('');
  log(`Project: \`${projectId}\``);
  log(`Generated by \`scripts/discover/discover.mjs\` (read-only).`);
  log('');
  log('---');
  log('');
  log('## BigQuery');
  log('');

  const bq = new BigQuery({ projectId });
  let datasets = [];
  try {
    [datasets] = await bq.getDatasets();
  } catch (err) {
    log(`> ⚠️ Could not list BigQuery datasets: ${err.message}`);
    log('');
    return;
  }

  if (datasets.length === 0) {
    log('_No BigQuery datasets found in this project._');
    log('');
    return;
  }

  log(`Found **${datasets.length}** dataset(s): ${datasets.map((d) => `\`${d.id}\``).join(', ')}`);
  log('');

  for (const ds of datasets) {
    log(`### Dataset: \`${ds.id}\``);
    log('');
    let tables = [];
    try {
      [tables] = await ds.getTables();
    } catch (err) {
      log(`> ⚠️ Could not list tables: ${err.message}`);
      log('');
      continue;
    }
    if (tables.length === 0) {
      log('_No tables._');
      log('');
      continue;
    }

    for (const t of tables) {
      let meta;
      try {
        [meta] = await t.getMetadata();
      } catch (err) {
        log(`#### \`${t.id}\` — ⚠️ metadata error: ${err.message}`);
        log('');
        continue;
      }
      const kind = meta.type || 'TABLE';
      const numRows = meta.numRows ?? '?';
      log(`#### \`${ds.id}.${t.id}\`  _(${kind}, ${numRows} rows)_`);
      log('');

      const fields = meta.schema?.fields ?? [];
      if (fields.length) {
        log('| column | type | mode |');
        log('|---|---|---|');
        for (const f of fields) {
          log(`| ${f.name} | ${f.type}${f.fields ? ' (nested)' : ''} | ${f.mode || 'NULLABLE'} |`);
        }
        log('');
      } else {
        log('_(no schema fields reported)_');
        log('');
      }

      // sample a few rows (skip views to avoid heavy scans where possible)
      try {
        const [rows] = await t.getRows({ maxResults: SAMPLE_ROWS });
        if (rows.length) {
          const cols = Object.keys(rows[0]);
          log('Sample rows:');
          log('');
          log('| ' + cols.join(' | ') + ' |');
          log('|' + cols.map(() => '---').join('|') + '|');
          for (const r of rows) {
            log('| ' + cols.map((c) => fmt(r[c])).join(' | ') + ' |');
          }
          log('');
        }
      } catch (err) {
        log(`> (sample skipped: ${err.message})`);
        log('');
      }
    }
  }
}

// ── Firestore ────────────────────────────────────────────────────────
function inferShape(data) {
  const shape = {};
  for (const [k, v] of Object.entries(data)) {
    let t = typeof v;
    if (v === null) t = 'null';
    else if (Array.isArray(v)) t = 'array';
    else if (v && typeof v === 'object') {
      if (typeof v.toDate === 'function') t = 'timestamp';
      else if (typeof v.latitude === 'number') t = 'geopoint';
      else t = 'map';
    }
    shape[k] = t;
  }
  return shape;
}

async function discoverFirestore() {
  log('---');
  log('');
  log('## Firestore');
  log('');

  const fs = new Firestore({ projectId });
  let collections = [];
  try {
    collections = await fs.listCollections();
  } catch (err) {
    log(`> ⚠️ Could not list Firestore collections: ${err.message}`);
    log('');
    return;
  }

  if (collections.length === 0) {
    log('_No root collections found._');
    log('');
    return;
  }

  log(`Found **${collections.length}** root collection(s): ${collections.map((c) => `\`${c.id}\``).join(', ')}`);
  log('');

  for (const col of collections) {
    log(`### Collection: \`${col.id}\``);
    log('');
    let snap;
    try {
      snap = await col.limit(SAMPLE_ROWS).get();
    } catch (err) {
      log(`> ⚠️ Could not read docs: ${err.message}`);
      log('');
      continue;
    }
    // count (best-effort, may be slow on huge collections — guard)
    let count = '?';
    try {
      const agg = await col.count().get();
      count = agg.data().count;
    } catch { /* ignore */ }
    log(`_~${count} doc(s)._`);
    log('');

    if (snap.empty) {
      log('_(empty)_');
      log('');
      continue;
    }

    // merged field shape across sampled docs
    const merged = {};
    for (const doc of snap.docs) {
      Object.assign(merged, inferShape(doc.data()));
    }
    log('Inferred fields:');
    log('');
    log('| field | type |');
    log('|---|---|');
    for (const [k, t] of Object.entries(merged)) log(`| ${k} | ${t} |`);
    log('');

    // one sample doc id + truncated json
    const first = snap.docs[0];
    log(`Sample doc \`${first.id}\`:`);
    log('');
    log('```json');
    log(fmt(JSON.stringify(first.data(), null, 2)).slice(0, 1500));
    log('```');
    log('');

    // note any subcollections on the first doc
    try {
      const subs = await first.ref.listCollections();
      if (subs.length) {
        log(`Subcollections of \`${first.id}\`: ${subs.map((s) => `\`${s.id}\``).join(', ')}`);
        log('');
      }
    } catch { /* ignore */ }
  }
}

// ── run ──────────────────────────────────────────────────────────────
try {
  await discoverBigQuery();
  await discoverFirestore();
  const outPath = resolve(REPO_ROOT, 'docs/EXISTING_SCHEMA.md');
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, out.join('\n'), 'utf8');
  console.log(`\n✅ Report written to ${outPath}`);
} catch (err) {
  console.error('Discovery failed:', err);
  process.exit(1);
}
